### ISSUE TITLE
transfer:validate failed

### ISSUE THREAD

**Issue by pwnyprod** [spryker-eco/fact-finder-ng#10]
vendor/bin/console transfer:validate
[warning] FactFinderNg.CartOrCheckoutEvent.count: integer is an invalid simple type
[warning] FactFinderNg.CartOrCheckoutEvent.price: integer is an invalid simple type

**Comment by zamo-po** [comment]
The issue is already known, thanks for create the PR. 
I'll let you know once it's fixed.

Related case:

- SUPESC-151

**Comment by pwnyprod** [comment]
is merged.
